spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:file:C:/tmp/testdb;AUTO_SERVER=TRUE
    username: sa
    password:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    clean-disabled: true
  


    


